version: '2.5'

services:
    currency-exchange:
        image: micro-28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8000:8000"
        networks: 
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
           rabbit_uri: amqp://guest:guest@rabbitmq:5672
           spring_rabbitmq_host: rabbitmq
           spring_zipkin_sender_type: rabbit
            
    naming-server:
        image: micro-28min/mmv2-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8761:8761"
        networks: 
          - currency-network
        
    currency-conversion:
        image: micro-28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8100:8100"
        networks: 
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
           rabbit_uri: amqp://guest:guest@rabbitmq:5672
           spring_rabbitmq_host: rabbitmq
           spring_zipkin_sender_type: rabbit
           
    api-gateway:
        image: micro-28min/mmv2-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8765:8765"
        networks: 
          - currency-network
        depends_on:
          - naming-server
          - rabbitmq
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
           rabbit_uri: amqp://guest:guest@rabbitmq:5672
           spring_rabbitmq_host: rabbitmq
           spring_zipkin_sender_type: rabbit
           
    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 300m
        ports:
          - "9411:9411"
        networks: 
          - currency-network
        depends_on:
          - rabbitmq
        environment:
          rabbit_uri: amqp://guest:guest@rabbitmq:5672
      
    rabbitmq:
        image: rabbitmq:3.8.12-management
        mem_limit: 300m
        ports:
          - "5672:5672"
          - "15672:15672" 
        networks: 
          - currency-network
 
networks:
  currency-network: