version: '2.5'

services:
    currency-exchange:
        image: micro-28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8000:8000"
        networks: 
          - currency-network
        depends_on:
          - naming-server
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
            
    naming-server:
        image: micro-28min/mmv2-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8761:8761"
        networks: 
          - currency-network
        
    currency-conversion:
        image: micro-28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8100:8100"
        networks: 
          - currency-network
        depends_on:
          - naming-server
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
           
    api-gateway:
        image: micro-28min/mmv2-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
          - "8765:8765"
        networks: 
          - currency-network
        depends_on:
          - naming-server
        environment:
           eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka/
           spring.zipkin.baseUrl: http://zipkin-server:9411
           
    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 300m
        ports:
          - "9411:9411"
        networks: 
          - currency-network
    rabbitmq:
        image: rabbitmq:3.8.12-management
        mem_limit: 300m
        ports:
          - "5672:5672"
        networks: 
          - currency-network
 
networks:
  currency-network: